version: '3.9'

services:
  rabbitmq:
    image: bitnami/rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    ports:
      - 15672:15672
      - 5672:5672
  activemq:
    image: webcenter/activemq:latest
    hostname: activemq
    restart: always
    environment:
      - ACTIVEMQ_NAME=activemq
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=password
    ports:
      - 61616:61616
      - 8161:8161
